name: test creation of the documentation
on: [push, pull_request]

jobs:
  test_documentation:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install sphinx
        run: pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          cd docs
          PATH="$(python -m site --user-base)/bin:$PATH" make
